
package Satellite_Control;

import simView.*;
import genDevs.plots.*;
import java.awt.*;
import java.lang.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;
import java.util.*;

public class SatelliteControlStationSystem extends ViewableDigraph {

	String in = "in";
	String out = "out";
	String f1 = "F1";
	String f2 = "F2";
	String f3 = "F3";
	String C1 = "C1";
	String Ca = "Ca";
	String scientificMessageInport = "scientificMessageIn";
	String satelliteRegularMessageInport = "satelliteRegualarMessageIn";
	String satelliteAlarmMessageInport = "satelliteAlarmMessageIn";
	String rawSatelliteAlarmMessageInport = "rawSatelliteAlarmMessageIn";
	String rawSatelliteRegularMessageInport = "rawSatelliteRegularMessageIn";
	String rawScientificMessageInport = "rawScientificMessageIn";
	public SatelliteControlStationSystem() {
		super("Satellite_ControlStation_System");

		addInport(in);
		addOutport(out);
		
		ViewableAtomic rawScientificExperienceMessageGenerator = 
				new RawScientificExperienceMessagesGenerator("RawScientificExperienceMessagesGenerator", 12);
		add(rawScientificExperienceMessageGenerator);
		
		ViewableAtomic rawRegularSatelliteControlMessageGenerator = 
				new RawRegularSatelliteControlMessageGenerator("RawRegularSatelliteControlMessageGenerator", 24);
		add(rawRegularSatelliteControlMessageGenerator);
		
		ViewableAtomic rawAlertSatelliteControlMessageGenerator = 
				new RawAlertSatelliteControlMessageGenerator("RawAlertSatelliteControlMessageGenerator", 40);
		add(rawAlertSatelliteControlMessageGenerator);
		

		ViewableAtomic F1Model = new F1(f1, 25);
		add(F1Model);
		
		ViewableAtomic F2Model = new F2(f2, 30);
		add(F2Model);
		
		
		ViewableAtomic C1Model = new C1("C1", 10);
		add(C1Model);

		ViewableAtomic F3Model = new F3(f3, 50);
		add(F3Model);
		
		ViewableAtomic CaModel = new Ca("Ca", 15);
		add(CaModel);
		addCoupling(this, in, rawScientificExperienceMessageGenerator, in);
		addCoupling(this, in, rawRegularSatelliteControlMessageGenerator, in);
		addCoupling(this, in, rawAlertSatelliteControlMessageGenerator, in);
		
		addCoupling(rawScientificExperienceMessageGenerator, out, F1Model, rawScientificMessageInport );
		addCoupling(rawRegularSatelliteControlMessageGenerator, out, F2Model, rawSatelliteRegularMessageInport);
		addCoupling(rawAlertSatelliteControlMessageGenerator, out, F3Model, rawSatelliteAlarmMessageInport);
		
		addCoupling(F1Model, out, C1Model, scientificMessageInport);
		addCoupling(F2Model, out, C1Model, satelliteRegularMessageInport);
		addCoupling(F3Model, out, CaModel, satelliteAlarmMessageInport);
		addCoupling(C1Model, out, this, out);
		addCoupling(CaModel, out, this, out);
	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1037, 490);
        if((ViewableComponent)withName("Ca")!=null)
             ((ViewableComponent)withName("Ca")).setPreferredLocation(new Point(669, 308));
        if((ViewableComponent)withName("F1")!=null)
             ((ViewableComponent)withName("F1")).setPreferredLocation(new Point(403, 176));
        if((ViewableComponent)withName("C1")!=null)
             ((ViewableComponent)withName("C1")).setPreferredLocation(new Point(647, 105));
        if((ViewableComponent)withName("RawRegularSatelliteControlMessageGenerator")!=null)
             ((ViewableComponent)withName("RawRegularSatelliteControlMessageGenerator")).setPreferredLocation(new Point(64, 66));
        if((ViewableComponent)withName("RawAlertSatelliteControlMessageGenerator")!=null)
             ((ViewableComponent)withName("RawAlertSatelliteControlMessageGenerator")).setPreferredLocation(new Point(78, 356));
        if((ViewableComponent)withName("F2")!=null)
             ((ViewableComponent)withName("F2")).setPreferredLocation(new Point(389, 30));
        if((ViewableComponent)withName("RawScientificExperienceMessagesGenerator")!=null)
             ((ViewableComponent)withName("RawScientificExperienceMessagesGenerator")).setPreferredLocation(new Point(73, 224));
        if((ViewableComponent)withName("F3")!=null)
             ((ViewableComponent)withName("F3")).setPreferredLocation(new Point(398, 377));
    }
}
