
package Fall2019ClassDemo;

import simView.*;
import genDevs.plots.*;
import java.awt.*;
import java.lang.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;
import java.util.*;

public class CarWashSys extends  ViewableDigraph{

public CarWashSys(){
super("CarWashSys");

addInport("in");
addOutport("out");

ViewableAtomic carG = new carGenerator("carGen",12);
add(carG);
ViewableAtomic truckG = new truckGenerator("truckGen",40);
add(truckG);
ViewableAtomic carWQ = new CarWashQ("CarWashQ",20);
add(carWQ);
ViewableAtomic trans = new transducer("transducer",500);
add(trans);


addCoupling(carG,"out",carWQ,"carIn");
addCoupling(truckG,"out",carWQ,"truckIn");
addCoupling(carG,"out",trans,"ariv");
addCoupling(truckG,"out",trans,"ariv");
addCoupling(carWQ,"out",trans,"solved");

addCoupling(carWQ,"out",this,"out");

}


    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(625, 341);
        if((ViewableComponent)withName("CarWashQ")!=null)
             ((ViewableComponent)withName("CarWashQ")).setPreferredLocation(new Point(256, 120));
        if((ViewableComponent)withName("carGen")!=null)
             ((ViewableComponent)withName("carGen")).setPreferredLocation(new Point(31, 39));
        if((ViewableComponent)withName("transducer")!=null)
             ((ViewableComponent)withName("transducer")).setPreferredLocation(new Point(264, 22));
        if((ViewableComponent)withName("truckGen")!=null)
             ((ViewableComponent)withName("truckGen")).setPreferredLocation(new Point(21, 156));
    }
}
